id: P50E727A0
initial_creation_type: input
source_metadata:
  title: Orgyen Tobgyal Rinpoche Series
  language: en
  description: 'Texts and teachings by Orgyen Tobgyal Rinpoche (o rgyan stobs rgyal,
    b. 1951), son of the Third Neten Chokling Rinpoche and renowned teacher of the
    Vajrayāna:'
  volume:
    9745c744294b4e51b122b77f8bfbd599:
      title: The Life of Jamyang Khyentse Wangpo
      parent: Biography
    ab0384045540443d91c9e6240addf578:
      title: A Brief History of the Sacred Image of White Tārā
      parent: History
    d6bddbb730a2410abf873114d0c79b60:
      title: Prayer for the Long Life of Orgyen Tobgyal Rinpoche
      parent: Long Life Prayers
    476b42be24534286b6184a973f74ee5d:
      title: The Excellent Stream of Nectar of Immortality
      parent: Long Life Prayers
    cbfccdfb6cb045549d33e2d80e590b7d:
      title: A Tribute to Tsewang Paljor
      parent: Biographies
    1bf9dc912ce2468f9a0361eb8c9ab6c3:
      title: The Life of Jamyang Khyentse Chökyi Lodrö
      parent: Biographies
    168eb9cfa55f42f7b9060d9a6c70b3e3:
      title: Invocation of the Vidyādhara Gurus
      parent: Prayers
    a616679e5b6a4c618ec9bdb09ea0a28e:
      title: Prayer to Khandro Tsering Chödrön
      parent: Prayers
created_at: '2022-03-01T01:08:30.485686'
last_modified_at: '2022-03-01T01:08:30.485692'
